version: '3.8'

services:
  exam-sev:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Postgres=Host=localhost; Database=postgres; Username=postgres; Password=282901
      - ConnectionStrings__Redis=redis:32771
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 282901
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
