services:
  examservice:
    build:
      context: ./  # Point to the parent directory of the Dockerfile
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=publish
      - DefaultConnection=Host=postgres;Database=postgres;Username=postgres;Password=282901  # Use the service name 'postgres' as the hostname
      - RedisConnection=redis:6379  # Use the service name 'redis' as the hostname
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 282901
    ports:
      - "5002:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
